### PR TITLE
test task

### PR DESCRIPTION
**Pull request by Tyav**
This is the Task for the required test to be prepared awaiting review. thank you

### CODE REVIEW

**Comment by mogbeyi-david** [comment]
Good looking question Moses. However for you guys to have a well arranged project structure, It would be nice if you put all your files in a folder and gave it an appropriate name.

**Comment by Tyav** [comment]
Okay Sir. would work on that right away. thanks for the heads up.

**Comment by Tyav** [comment]
Folder has been created, and awaiting approval for merge.

**Review by mogbeyi-david — APPROVED** [review]

**Comment by mogbeyi-david** [comment]
I have approved the changes. If your colleagues are okay with it, they can go ahead and merge

**Review by dearests — APPROVED** [review]

**Pull request merged**
